# Generated by Django 2.2.5 on 2020-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('1', 'Educational'), ('2', 'Music'), ('3', 'Comedy')], max_length=25, null=True),
        ),
    ]
