# Generated by Django 2.2.5 on 2020-02-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='number_of_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
